name: samuraimoney
favicon: null
layout_spectrum: 0.02848406881093979
typography_spectrum: 0.4039483377709985
title: Samurai Money
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75791708-4
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.15282105444930494
  lightness: 0.39754474395886064
  saturation: 0.6383282318711281
  rhythmicContrast: 0.03560750023461878
purpose: []
